import { useState } from 'react';
import { Modal, Button } from 'antd';
import { AgGridReact } from 'ag-grid-react';
import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-alpine.css';


const MyModalWithAGGrid = () => {
    const [isModalVisible, setIsModalVisible] = useState(false);
    const rowData = [
        { Ship_Date: "2024-05-20", Order_Date: "2024-05-15" },
        { Ship_Date: "2024-05-21", Order_Date: "2024-05-16" },
        
    ];

    const dataDictionary = [
        {
            "column_name": "Returned",
            "column_alias": "Returned",
            "column_type": "Dimension",
            "unit": null,
            "formula": null,
            "column_table_name": "a908596b89506d466f225125ea05d8a3",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "NA",
            "column_table_alias": "Returns",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382797,
            "column_is_pre_calculated": false,
            "column_datatype_name": "varchar",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null,
            "color": "#fffeee",
            "thousand_separator": true,
            "unit": "$",
            "formatter_text_position": "Left",
            "precision": 2,
            "formatting_type": "123,456,789",
            "abbreviation": ["Numeric", "billions"]
        },
        {
            "column_name": "Order_ID",
            "column_alias": "Order ID",
            "column_type": "Dimension",
            "unit": null,
            "formula": null,
            "column_table_name": "a908596b89506d466f225125ea05d8a3",
            "column_is_active": false,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "NA",
            "column_table_alias": "Returns",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382798,
            "column_is_pre_calculated": false,
            "column_datatype_name": "varchar",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null,
            "unit": "-"
        },
        {
            "column_name": "Row_ID",
            "column_alias": "Row ID",
            "column_type": "Measure",
            "unit": null,
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": false,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "DESC",
            "default_agg_type": "Sum",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382799,
            "column_is_pre_calculated": false,
            "column_datatype_name": "integer",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null,
            "unit": "-"
        },
        {
            "column_name": "Order_ID",
            "column_alias": "Order ID2",
            "column_type": "Dimension",
            "unit": null,
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": false,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "NA",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382800,
            "column_is_pre_calculated": false,
            "column_datatype_name": "varchar",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null,
            "unit": "-"
        },
        {
            "column_name": "Order_Date",
            "column_alias": "Order Date",
            "column_type": "Dimension",
            "unit": null,
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "ASC",
            "default_agg_type": "NA",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382801,
            "column_is_pre_calculated": false,
            "column_datatype_name": "timestamp",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null,
            "unit": "-"
        },
        {
            "column_name": "Ship_Date",
            "column_alias": "Ship Date",
            "column_type": "Dimension",
            "unit": null,
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": true,
            "column_default_order": "ASC",
            "default_agg_type": "NA",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382802,
            "column_is_pre_calculated": false,
            "column_datatype_name": "timestamp",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null,
            "unit": "-"
        },
        {
            "column_name": "Ship_Mode",
            "column_alias": "Ship Mode",
            "column_type": "Dimension",
            "unit": null,
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "NA",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382803,
            "column_is_pre_calculated": false,
            "column_datatype_name": "varchar",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null,
            "unit": "-"
        },
        {
            "column_name": "Customer_ID",
            "column_alias": "Customer ID",
            "column_type": "Dimension",
            "unit": null,
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": false,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "NA",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382804,
            "column_is_pre_calculated": false,
            "column_datatype_name": "varchar",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null,
            "unit": "-"
        },
        {
            "column_name": "Customer_Name",
            "column_alias": "Customer Name",
            "column_type": "Dimension",
            "unit": null,
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "NA",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382805,
            "column_is_pre_calculated": false,
            "column_datatype_name": "varchar",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null,
            "unit": "-"
        },
        {
            "column_name": "Segment",
            "column_alias": "Segment",
            "column_type": "Dimension",
            "unit": null,
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "NA",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382806,
            "column_is_pre_calculated": false,
            "column_datatype_name": "varchar",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null
        },
        {
            "column_name": "Country",
            "column_alias": "Country",
            "column_type": "Dimension",
            "unit": null,
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "NA",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382807,
            "column_is_pre_calculated": false,
            "column_datatype_name": "varchar",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null
        },
        {
            "column_name": "City",
            "column_alias": "City",
            "column_type": "Dimension",
            "unit": null,
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "NA",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382808,
            "column_is_pre_calculated": false,
            "column_datatype_name": "varchar",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null
        },
        {
            "column_name": "State",
            "column_alias": "State",
            "column_type": "Dimension",
            "unit": null,
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "NA",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382809,
            "column_is_pre_calculated": false,
            "column_datatype_name": "varchar",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null
        },
        {
            "column_name": "Postal_Code",
            "column_alias": "Postal Code",
            "column_type": "Measure",
            "unit": "#",
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "DESC",
            "default_agg_type": "Count",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "prefix",
            "sch_metadata_id": 10382810,
            "column_is_pre_calculated": false,
            "column_datatype_name": "integer",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null
        },
        {
            "column_name": "Region",
            "column_alias": "Region",
            "column_type": "Dimension",
            "unit": null,
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "NA",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382811,
            "column_is_pre_calculated": false,
            "column_datatype_name": "varchar",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null
        },
        {
            "column_name": "Product_ID",
            "column_alias": "Product ID",
            "column_type": "Dimension",
            "unit": null,
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": false,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "NA",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382812,
            "column_is_pre_calculated": false,
            "column_datatype_name": "varchar",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null
        },
        {
            "column_name": "Category",
            "column_alias": "Category",
            "column_type": "Dimension",
            "unit": null,
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "NA",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382813,
            "column_is_pre_calculated": false,
            "column_datatype_name": "varchar",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null
        },
        {
            "column_name": "Sub_Category",
            "column_alias": "Sub Category",
            "column_type": "Dimension",
            "unit": null,
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "NA",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382814,
            "column_is_pre_calculated": false,
            "column_datatype_name": "varchar",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null
        },
        {
            "column_name": "Product_Name",
            "column_alias": "Product Name",
            "column_type": "Dimension",
            "unit": null,
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "NA",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382815,
            "column_is_pre_calculated": false,
            "column_datatype_name": "varchar",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null
        },
        {
            "column_name": "Sales",
            "column_alias": "Sales",
            "column_type": "Measure",
            "unit": "$",
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "DESC",
            "default_agg_type": "Sum",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "prefix",
            "sch_metadata_id": 10382816,
            "column_is_pre_calculated": false,
            "column_datatype_name": "float",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null
        },
        {
            "column_name": "Quantity",
            "column_alias": "Quantity",
            "column_type": "Measure",
            "unit": "#",
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "DESC",
            "default_agg_type": "Count",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "prefix",
            "sch_metadata_id": 10382817,
            "column_is_pre_calculated": false,
            "column_datatype_name": "integer",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null
        },
        {
            "column_name": "Discount",
            "column_alias": "Discount",
            "column_type": "Measure",
            "unit": null,
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "DESC",
            "default_agg_type": "Sum",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382818,
            "column_is_pre_calculated": false,
            "column_datatype_name": "float",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null
        },
        {
            "column_name": "Profit",
            "column_alias": "Profit",
            "column_type": "Measure",
            "unit": "$",
            "formula": null,
            "column_table_name": "d5091672c28afadb8278c2032eb2ad71",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "DESC",
            "default_agg_type": "Sum",
            "column_table_alias": "Orders",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "prefix",
            "sch_metadata_id": 10382819,
            "column_is_pre_calculated": false,
            "column_datatype_name": "float",
            "is_auto_generated": false,
            "lrf_query_lang_id": 1,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Order Date year",
            "column_type": "vDimension",
            "unit": " ",
            "formula": "CUSTOMSORT(TO_CHAR([[10382801]], 'YYYY'), TO_CHAR([[10382801]], 'YYYY'))",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "ASC",
            "default_agg_type": "NA",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382820,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": true,
            "lrf_query_lang_id": 3,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Order Date quarter",
            "column_type": "vDimension",
            "unit": " ",
            "formula": "CUSTOMSORT('Q'||TO_CHAR([[10382801]], 'Q-YYYY'), TO_CHAR([[10382801]], 'YYYYQ'))",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "ASC",
            "default_agg_type": "NA",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382821,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": true,
            "lrf_query_lang_id": 3,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Order Date month",
            "column_type": "vDimension",
            "unit": " ",
            "formula": "CUSTOMSORT(TO_CHAR([[10382801]], 'Mon-YYYY'), TO_CHAR([[10382801]], 'YYYYMM'))",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "ASC",
            "default_agg_type": "NA",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382822,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": true,
            "lrf_query_lang_id": 3,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Order Date week",
            "column_type": "vDimension",
            "unit": " ",
            "formula": "CUSTOMSORT('W'||TO_CHAR([[10382801]], 'WW-YYYY'), TO_CHAR([[10382801]], 'YYYYWW'))",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "ASC",
            "default_agg_type": "NA",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382823,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": true,
            "lrf_query_lang_id": 3,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Order Date day",
            "column_type": "vDimension",
            "unit": " ",
            "formula": "CUSTOMSORT(TO_CHAR([[10382801]], 'Day'), TO_CHAR([[10382801]], 'D'))",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "ASC",
            "default_agg_type": "NA",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382824,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": true,
            "lrf_query_lang_id": 3,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Ship Date year",
            "column_type": "vDimension",
            "unit": " ",
            "formula": "CUSTOMSORT(TO_CHAR([[10382802]], 'YYYY'), TO_CHAR([[10382802]], 'YYYY'))",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "ASC",
            "default_agg_type": "NA",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382825,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": true,
            "lrf_query_lang_id": 3,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Ship Date quarter",
            "column_type": "vDimension",
            "unit": " ",
            "formula": "CUSTOMSORT('Q'||TO_CHAR([[10382802]], 'Q-YYYY'), TO_CHAR([[10382802]], 'YYYYQ'))",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "ASC",
            "default_agg_type": "NA",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382826,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": true,
            "lrf_query_lang_id": 3,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Ship Date month",
            "column_type": "vDimension",
            "unit": " ",
            "formula": "CUSTOMSORT(TO_CHAR([[10382802]], 'Mon-YYYY'), TO_CHAR([[10382802]], 'YYYYMM'))",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "ASC",
            "default_agg_type": "NA",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382827,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": true,
            "lrf_query_lang_id": 3,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Ship Date week",
            "column_type": "vDimension",
            "unit": " ",
            "formula": "CUSTOMSORT('W'||TO_CHAR([[10382802]], 'WW-YYYY'), TO_CHAR([[10382802]], 'YYYYWW'))",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "ASC",
            "default_agg_type": "NA",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382828,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": true,
            "lrf_query_lang_id": 3,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Ship Date day",
            "column_type": "vDimension",
            "unit": " ",
            "formula": "CUSTOMSORT(TO_CHAR([[10382802]], 'Day'), TO_CHAR([[10382802]], 'D'))",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "ASC",
            "default_agg_type": "NA",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382829,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": true,
            "lrf_query_lang_id": 3,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Discounted Profit",
            "column_type": "Measure",
            "unit": "",
            "formula": "[[10382819]]*(1-([[10382818]]/100))",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "Sum",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382830,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": false,
            "lrf_query_lang_id": 4,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Shipping Cost Per Unit",
            "column_type": "Measure",
            "unit": "",
            "formula": "[[10382816]]/[[10382817]]",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "Sum",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382831,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": false,
            "lrf_query_lang_id": 4,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Profit Per Quantity",
            "column_type": "Measure",
            "unit": "",
            "formula": "[[10382819]]/[[10382817]]",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "Sum",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382832,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": false,
            "lrf_query_lang_id": 4,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Returned Items",
            "column_type": "Measure",
            "unit": "",
            "formula": "CASE WHEN [[10382797]] = 'YES' THEN 1 ELSE 0 END",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "Sum",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382833,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": false,
            "lrf_query_lang_id": 4,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Order Time",
            "column_type": "Measure",
            "unit": "",
            "formula": "HOUR([[10382801]])",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "Sum",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382834,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": false,
            "lrf_query_lang_id": 4,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Sales Revenue Percentage by Region",
            "column_type": "Measure",
            "unit": "",
            "formula": "([[10382816]]/SUM([[10382816]]) OVER (PARTITION BY [[10382811]]))*100",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "Sum",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382835,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": false,
            "lrf_query_lang_id": 4,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Profit by Category",
            "column_type": "Measure",
            "unit": "",
            "formula": "SUM([[10382819]]) OVER (PARTITION BY [[10382813]])",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "Sum",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382836,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": false,
            "lrf_query_lang_id": 4,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Order Processing Time",
            "column_type": "Measure",
            "unit": "",
            "formula": "DATEDIFF(DAY,[[10382801]],[[10382802]])",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "Sum",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382851,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": false,
            "lrf_query_lang_id": 4,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Returned Indicator",
            "column_type": "Measure",
            "unit": "",
            "formula": "CASE WHEN [[10382797]] = 'YES' THEN 1 ELSE 0 END",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "Sum",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382852,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": false,
            "lrf_query_lang_id": 4,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Category Profit Margin",
            "column_type": "Measure",
            "unit": "",
            "formula": "([[10382819]]/NULLIF([[10382816]],0))*100",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "Sum",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382853,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": false,
            "lrf_query_lang_id": 4,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Shipping Delay Time",
            "column_type": "Measure",
            "unit": "",
            "formula": "DATEDIFF(DAY,[[10382802]],GETDATE())",
            "column_table_name": "-",
            "column_is_active": false,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "Sum",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382854,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": false,
            "lrf_query_lang_id": 4,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Discount Percentage",
            "column_type": "Measure",
            "unit": "",
            "formula": "([[10382818]]/NULLIF([[10382816]],0))*100",
            "column_table_name": "-",
            "column_is_active": false,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "Sum",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382856,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": false,
            "lrf_query_lang_id": 4,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "Profit Margin",
            "column_type": "Measure",
            "unit": "",
            "formula": "([[10382819]]/NULLIF([[10382816]], 0))*100",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "Sum",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10382894,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": false,
            "lrf_query_lang_id": 4,
            "date_format": null
        },
        {
            "column_name": null,
            "column_alias": "sales2",
            "column_type": "vCalculated KPI",
            "unit": "",
            "formula": "SUM([[10382816]])*4",
            "column_table_name": "-",
            "column_is_active": true,
            "sch_schema_id": 24107,
            "column_is_date": false,
            "column_default_order": "NA",
            "default_agg_type": "NA",
            "column_table_alias": "-",
            "enable_for_filter": false,
            "what_if_max": null,
            "what_if_min": null,
            "what_if_step": null,
            "column_custom_datatype": null,
            "unit_placement": "suffix",
            "sch_metadata_id": 10383286,
            "column_is_pre_calculated": false,
            "column_datatype_name": null,
            "is_auto_generated": false,
            "lrf_query_lang_id": 3,
            "date_format": null
        }
    ]


    // const actionTaken = () => {
    //     alert('button are wokring');
    // }

    const createColumnDefs = (data) => {
        const filteredColumns = data
            .filter((item) => item.column_datatype_name === "timestamp")
            .map((item) => ({
                headerName: item.column_alias || item.column_name,
                field: item.column_name,
                type: item.column_type === "Dimension" ? "dimension" : "measure",
                sortable: item.column_is_active,
                filter: item.enable_for_filter,
                resizable: true,
                hide: !item.column_is_active,
            }));

        const checkboxColumn = {
            headerName: "checkBox",
            field: "checkBox",
            checkboxSelection: true,
            headerCheckboxSelection: true,
            width: 100,
            suppressMenu: true,
            sortable: false,
            filter: false,
            resizable: false,
        };

        // const button = {

        //     headerName : "click me",
        //     field : " buttons ",
        //     width: 150,
        //     suppressMenu: true,
        //     sortable: false,
        //     filter: false,
        //     resizable: false,
        //     cellRenderer: p => {
        //         return (
        //             <div>
        //                 <button onClick={() => { actionTaken(p) }}> Click me to buy</button>
        //             </div>
        //         )
        //     }
        // }
        

        return [ checkboxColumn, ...filteredColumns];
    };

    const columnDefs = createColumnDefs(dataDictionary);

    const showModal = () => {
        setIsModalVisible(true);
    };

    const handleOk = () => {
        setIsModalVisible(false);
    };

    const handleCancel = () => {
        setIsModalVisible(false);
    };

    return (
        <div>
            <Button type="primary" onClick={showModal}>
                Open Modal with AG Grid
            </Button>
            <Modal
                title="AG Grid in Ant Design Modal"
                visible={isModalVisible}
                onOk={handleOk}
                onCancel={handleCancel}
                width={800}
            >
                <div className="ag-theme-alpine" style={{ height: 400, width: '100%' }}>
                    <AgGridReact
                        rowData={rowData}
                        columnDefs={columnDefs}
                        defaultColDef={{ sortable: true, filter: true, resizable: true, CheckboxSelection : true}}
                    />
                </div>
            </Modal>
        </div>
    );
};

export default MyModalWithAGGrid;
